#!/bin/bash
# -*- coding: utf-8 -*-
# vim: set fileencoding=utf-8
# Copyright (c) 2007 Pär Andersson (National Supercomputer Centre, Sweden),
# 2011 Joerg Bornschein <bornschein@fias.uni-frankfurt.de>,
# 2014-2016 Janne Blomqvist  <janne.blomqvist@aalto.fi>
# CHANGES
# 2023 Jason <yalim@asu.edu>
#
# This will submit a batch script that starts screen on a node.
# Then ssh is used to connect to the node and attach the screen.
# The result is very similar to an interactive shell in PBS
# (qsub -I)

if [[ ! -z $SIF ]]; then
  SIF_PATH=$(realpath $SIF)
elif [[ ! -z $SIMG ]]; then
  if [[ $SIMG != *.sif ]]; then
    SIMG="$SIMG.sif"
  fi

  SHARED_SIF=$(realpath /packages/apps/simg/$SIMG)
  INDIV_SIF=$(realpath $SIMG)

  if [ -f "$SHARED_SIF" ]; then
    SIF_PATH=$SHARED_SIF
  elif [ -f "$INDIV_SIF" ]; then
    SIF_PATH=$INDIV_SIF
  else
    echo "Cannot find image file, aborting."
    exit 1
  fi
fi

readonly MYDIR="$(dirname "$(readlink -f ${BASH_SOURCE[0]})")"

# Batch Script that starts SCREEN
readonly BS=$MYDIR/_interactive
# Interactive screen script
IS=$MYDIR/_interactive_screen

# Default partition (Change this to suit your site!)
# The user can specify another partition explicitly, sbatch will take
# the last one on the command line.
readonly DEFAULTPART=public
readonly DEFAULTQOS=public
readonly DEFAULTTIME="0-04:00:00"

readonly sbatch_opts=(
  --parsable 
  --output=/dev/null 
  --error=/dev/null 
  -p $DEFAULTPART 
  -q $DEFAULTQOS 
  -t $DEFAULTTIME 
  $@ 
  $BS
)


# Submit the job and get the job id
readonly JOB=$(sbatch "${sbatch_opts[@]}" | grep --line-buffered -Eoe "\b[0-9]+$")

# Make sure the job is always canceled
trap "{ scancel --quiet $JOB; exit; }" SIGINT SIGTERM EXIT

echo "Waiting for JOBID $JOB to start"
while true; do
  sleep 1s
  # Check job status
  status=$(squeue -j $JOB -t PD,R -h -o %t)
  if [ "$status" = "R" ];then
    # Job is running, break the while loop
    break
  elif [ "$status" != "PD" ];then
    echo "Job is not Running or Pending. Aborting"
    #squeue
    #scancel $JOB
    #exit 1
  fi
  echo -n "."
done

# Determine the first node in the job:
readonly NODE=$(scontrol show job $JOB|perl -ne 'print "$1" if /BatchHost=(.+)\s/')

# SSH to the node and attach the screen
sleep 1s

if [[ $SIMG =~ gromacs* ]]; then
  EXECMODE="run --nv"
  APPRUN=""
else
  EXECMODE="exec"
  APPRUN="/bin/bash"
fi

if [[ ! -z $SIF_PATH ]]; then
  IS="exec /usr/bin/apptainer $EXECMODE -B /scratch/$USER:/scratch/$USER $SIF_PATH $APPRUN"
  ssh -X -t $NODE "$IS"
else
  ssh -X -t $NODE $IS slurm$JOB
fi

# The trap will now cancel the job before exiting.

